import type { Employee } from "./types";

export const mockEmployees: Employee[] = [
  {
    id: "1",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@company.com",
    jobTitle: "Software Engineer",
    hireDate: "2022-03-15",
  },
  {
    id: "2",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@company.com",
    jobTitle: "Product Manager",
    hireDate: "2021-07-01",
  },
  {
    id: "3",
    firstName: "Carol",
    lastName: "Williams",
    email: "carol.williams@company.com",
    jobTitle: "UX Designer",
    hireDate: "2023-01-10",
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@company.com",
    jobTitle: "DevOps Engineer",
    hireDate: "2020-11-20",
  },
  {
    id: "5",
    firstName: "Eva",
    lastName: "Martinez",
    email: "eva.martinez@company.com",
    jobTitle: "Data Analyst",
    hireDate: "2023-05-08",
  },
  {
    id: "6",
    firstName: "Frank",
    lastName: "Garcia",
    email: "frank.garcia@company.com",
    jobTitle: "Backend Developer",
    hireDate: "2022-09-12",
  },
  {
    id: "7",
    firstName: "Grace",
    lastName: "Lee",
    email: "grace.lee@company.com",
    jobTitle: "Frontend Developer",
    hireDate: "2021-02-28",
  },
  {
    id: "8",
    firstName: "Henry",
    lastName: "Wilson",
    email: "henry.wilson@company.com",
    jobTitle: "QA Engineer",
    hireDate: "2023-08-14",
  },
  {
    id: "9",
    firstName: "Iris",
    lastName: "Taylor",
    email: "iris.taylor@company.com",
    jobTitle: "Scrum Master",
    hireDate: "2022-06-01",
  },
  {
    id: "10",
    firstName: "Jack",
    lastName: "Anderson",
    email: "jack.anderson@company.com",
    jobTitle: "Solutions Architect",
    hireDate: "2020-04-22",
  },
  {
    id: "11",
    firstName: "Karen",
    lastName: "Thomas",
    email: "karen.thomas@company.com",
    jobTitle: "Technical Writer",
    hireDate: "2023-03-18",
  },
  {
    id: "12",
    firstName: "Liam",
    lastName: "Jackson",
    email: "liam.jackson@company.com",
    jobTitle: "Security Engineer",
    hireDate: "2021-10-05",
  },
  {
    id: "13",
    firstName: "Mia",
    lastName: "White",
    email: "mia.white@company.com",
    jobTitle: "Mobile Developer",
    hireDate: "2022-12-01",
  },
  {
    id: "14",
    firstName: "Noah",
    lastName: "Harris",
    email: "noah.harris@company.com",
    jobTitle: "Database Admin",
    hireDate: "2020-08-30",
  },
  {
    id: "15",
    firstName: "Olivia",
    lastName: "Clark",
    email: "olivia.clark@company.com",
    jobTitle: "Engineering Manager",
    hireDate: "2019-06-15",
  },
];
